/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./components/common/BaseButton.vue')['default']
    BaseDropdown: typeof import('./components/common/BaseDropdown.vue')['default']
    BaseInput: typeof import('./components/common/BaseInput.vue')['default']
    CharacterItem: typeof import('./components/characters/character/CharacterItem.vue')['default']
    CharacterItemModal: typeof import('./components/characters/character/CharacterItemModal.vue')['default']
    CharactersFilters: typeof import('./components/characters/CharactersFilters.vue')['default']
    CharactersList: typeof import('./components/characters/CharactersList.vue')['default']
    CharactersPageRange: typeof import('./components/characters/CharactersPageRange.vue')['default']
    NavigationButtons: typeof import('./components/navigation/NavigationButtons.vue')['default']
    PageFooter: typeof import('./components/layout/PageFooter.vue')['default']
    PageHeader: typeof import('./components/layout/PageHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
